
//
// tokens.swift
//

// File generated by the Figma Token Engine
// Do not edit directly


import SwiftUI

public struct Tokens {
  public struct Coppel {
    public struct Light {
      public static let themesButtonBackgroundPrimary = UIColor(red: 0.780, green: 0.725, blue: 1.000, alpha: 1)
      public static let themesButtonBorderPrimary = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
      public static let themesButtonForegroundPrimary = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
      public static let themesColorBrand = UIColor(red: 0.780, green: 0.725, blue: 1.000, alpha: 1)
    }
    public struct Dark {
      public static let themesButtonBackgroundPrimary = UIColor(red: 0.780, green: 0.725, blue: 1.000, alpha: 1)
      public static let themesButtonBorderPrimary = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
      public static let themesButtonForegroundPrimary = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
      public static let themesColorBrand = UIColor(red: 0.780, green: 0.725, blue: 1.000, alpha: 1)
    }
  }
  public struct Bancoppel {
    public struct Light {
      public static let themesButtonBackgroundPrimary = UIColor(red: 0.780, green: 0.725, blue: 1.000, alpha: 1)
      public static let themesButtonBorderPrimary = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
      public static let themesButtonForegroundPrimary = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
      public static let themesColorBrand = UIColor(red: 0.780, green: 0.725, blue: 1.000, alpha: 1)
    }
    public struct Dark {
      public static let themesButtonBackgroundPrimary = UIColor(red: 0.780, green: 0.725, blue: 1.000, alpha: 1)
      public static let themesButtonBorderPrimary = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
      public static let themesButtonForegroundPrimary = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
      public static let themesColorBrand = UIColor(red: 0.780, green: 0.725, blue: 1.000, alpha: 1)
    }
  }
}